DROP DATABASE IF EXISTS blog_db;
CREATE DATABASE blog_db;

USE blog_db;

CREATE TABLE blogs (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(30) NOT NULL UNIQUE,
    para1 TEXT NOT NULL,
    para2 TEXT,
    para3 TEXT,
    datetime DATE NOT NULL
);

